import Testing
@testable import ClipdCore

// Every case below mirrors a real measurement recorded in NOTES.md.

@Test("Ordinary Chrome text is stored")
func storesOrdinaryText() {
    let snap = PasteboardSnapshot(
        types: ["public.html", "public.utf8-plain-text",
                "org.chromium.source-url"],
        totalBytes: 1298, itemCount: 1, sourceBundleID: "com.google.Chrome")
    #expect(decideCapture(snap, settings: .standard) == .store)
}

@Test("Bitwarden marks its copies, so the marker refuses it")
func refusesConcealedMarker() {
    // Measured: Bitwarden writes utf8-plain-text plus ConcealedType.
    let snap = PasteboardSnapshot(
        types: ["public.utf8-plain-text", "org.nspasteboard.ConcealedType"],
        totalBytes: 15, itemCount: 1, sourceBundleID: "com.bitwarden.desktop")
    #expect(decideCapture(snap, settings: .standard)
            == .refuse(.concealedMarker("org.nspasteboard.ConcealedType")))
}

@Test("Apple Passwords sets NO marker, so only the deny-list saves us")
func refusesDeniedAppWithNoMarker() {
    // Measured: a real password copy was a bare 20 byte utf8-plain-text with
    // no ConcealedType, no TransientType and no source marker. If this test
    // ever passes for the wrong reason, passwords land in the database.
    let snap = PasteboardSnapshot(
        types: ["public.utf8-plain-text"],
        totalBytes: 20, itemCount: 1, sourceBundleID: "com.apple.Passwords")
    #expect(decideCapture(snap, settings: .standard)
            == .refuse(.deniedApp("com.apple.Passwords")))
}

@Test("A clipboard change carrying zero items is never stored")
func refusesEmptyChange() {
    // Measured: Passwords.app wipes the clipboard 60s after a copy, and the
    // wipe arrives as a normal change with zero items, attributed to whatever
    // app happened to be frontmost. Storing it would create blank rows and
    // blame an innocent app.
    let snap = PasteboardSnapshot(
        types: [], totalBytes: 0, itemCount: 0,
        sourceBundleID: "com.apple.Terminal")
    #expect(decideCapture(snap, settings: .standard) == .refuse(.emptyChange))
}

@Test("Transient and auto generated markers are also refused")
func refusesOtherMarkers() {
    let transient = PasteboardSnapshot(
        types: ["public.utf8-plain-text", "org.nspasteboard.TransientType"],
        totalBytes: 10, itemCount: 1, sourceBundleID: "com.example.app")
    #expect(decideCapture(transient, settings: .standard)
            == .refuse(.concealedMarker("org.nspasteboard.TransientType")))

    let auto = PasteboardSnapshot(
        types: ["public.utf8-plain-text", "org.nspasteboard.AutoGeneratedType"],
        totalBytes: 10, itemCount: 1, sourceBundleID: "com.example.app")
    #expect(decideCapture(auto, settings: .standard)
            == .refuse(.concealedMarker("org.nspasteboard.AutoGeneratedType")))
}

@Test("Oversized items are refused with the numbers attached")
func refusesTooLarge() {
    let snap = PasteboardSnapshot(
        types: ["public.png"], totalBytes: 20_000_000, itemCount: 1,
        sourceBundleID: "com.apple.Preview")
    #expect(decideCapture(snap, settings: .standard)
            == .refuse(.tooLarge(bytes: 20_000_000, cap: 10 * 1024 * 1024)))
}

@Test("A typical screenshot is well under the cap and is stored")
func storesScreenshot() {
    // Measured: a full screen retina grab arrives as public.png at 2.81 MB.
    let snap = PasteboardSnapshot(
        types: ["public.png"], totalBytes: 2_942_549, itemCount: 1,
        sourceBundleID: "com.apple.screencaptureui")
    #expect(decideCapture(snap, settings: .standard) == .store)
}

@Test("An item with types but no usable content is refused")
func refusesNoUsableContent() {
    let snap = PasteboardSnapshot(
        types: ["com.example.private.flavour"], totalBytes: 4, itemCount: 1,
        sourceBundleID: "com.example.app")
    #expect(decideCapture(snap, settings: .standard)
            == .refuse(.noUsableContent))
}

@Test("An unknown source app does not block an otherwise good item")
func storesWithNilSource() {
    let snap = PasteboardSnapshot(
        types: ["public.utf8-plain-text"], totalBytes: 12, itemCount: 1,
        sourceBundleID: nil)
    #expect(decideCapture(snap, settings: .standard) == .store)
}

@Test("The deny-list is matched case insensitively")
func denyListIsCaseInsensitive() {
    // Bundle ids are case insensitive on macOS. A deny-list that misses
    // because of capitalisation is a silent password leak.
    let snap = PasteboardSnapshot(
        types: ["public.utf8-plain-text"], totalBytes: 20,
        itemCount: 1, sourceBundleID: "COM.APPLE.PASSWORDS")
    #expect(decideCapture(snap, settings: .standard)
            == .refuse(.deniedApp("COM.APPLE.PASSWORDS")))
}

@Test("The shipped deny-list covers the managers we measured")
func standardDenyList() {
    let ids = CaptureSettings.standard.deniedBundleIDs
    #expect(ids.contains("com.apple.passwords"))
    #expect(ids.contains("com.apple.keychainaccess"))
    #expect(ids.contains("com.bitwarden.desktop"))
    #expect(ids.contains("com.1password.1password"))
}

@Test("Zero byte content with a real type is still refused")
func refusesZeroBytes() {
    // Degenerate case: a type is advertised but carries nothing.
    let snap = PasteboardSnapshot(
        types: ["public.utf8-plain-text"], totalBytes: 0, itemCount: 1,
        sourceBundleID: "com.example.app")
    #expect(decideCapture(snap, settings: .standard)
            == .refuse(.noUsableContent))
}
