/// Why an item was not saved.
///
/// A boolean would be cheaper and wrong. "Why was this not saved" has at least
/// five answers, and if the app cannot tell them apart then neither can the
/// settings screen or anyone debugging it.
public enum CaptureRefusal: Equatable, Sendable {
    case emptyChange
    case concealedMarker(String)
    case deniedApp(String)
    case tooLarge(bytes: Int, cap: Int)
    case noUsableContent
}

public enum CaptureDecision: Equatable, Sendable {
    case store
    case refuse(CaptureRefusal)
}

/// Markers a producer sets to say "do not record this".
///
/// Measured: Bitwarden honours ConcealedType. Apple's Passwords.app honours
/// nothing at all, which is why this check cannot be the only defence.
public let concealedMarkerTypes: [String] = [
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
]

/// Types we can actually do something with. Anything else is an app's private
/// flavour and is not worth a history entry on its own.
private let usableTypes: [String] = [
    "public.utf8-plain-text",
    "public.plain-text",
    "NSStringPboardType",
    "public.html",
    "public.rtf",
    "public.png",
    "public.tiff",
    "public.jpeg",
    "public.file-url",
    "public.url",
]

public func decideCapture(_ snapshot: PasteboardSnapshot,
                          settings: CaptureSettings) -> CaptureDecision {
    // 1. Empty first, always. A cleared clipboard is a real event, it carries
    //    no content, and its source app is an innocent bystander. Measured:
    //    Passwords.app clears 60s after a copy and it was blamed on Terminal.
    if snapshot.itemCount == 0 || snapshot.types.isEmpty {
        return .refuse(.emptyChange)
    }

    // 2. The producer's own signal, where it exists.
    for marker in concealedMarkerTypes where snapshot.types.contains(marker) {
        return .refuse(.concealedMarker(marker))
    }

    // 3. The deny-list. This is the layer that catches Apple.
    if let source = snapshot.sourceBundleID,
       settings.deniedBundleIDs.contains(source.lowercased()) {
        return .refuse(.deniedApp(source))
    }

    // 4. Size. Reported with the numbers so the reason is actionable.
    if snapshot.totalBytes > settings.maxBytes {
        return .refuse(.tooLarge(bytes: snapshot.totalBytes,
                                 cap: settings.maxBytes))
    }

    // 5. Something we can actually store, and it must have bytes.
    let hasUsable = snapshot.types.contains { usableTypes.contains($0) }
    guard hasUsable, snapshot.totalBytes > 0 else {
        return .refuse(.noUsableContent)
    }

    return .store
}
